### ISSUE TITLE
$serverurl Update

### ISSUE THREAD

**Issue by Nerd-Turtle** [Bachperson/Bedrock-Server-Updater#1]
Mojang appears to have changed the URL used for hosting the downloads, resulting in a "ERROR: Web request did not return expected content."

$serverurl = $requestResult.Links | select href | where {$_.href -like "https://www.minecraft.net/bedrockdedicatedserver/bin-win/bedrock-server*"}

$filename = $url.Replace("https://www.minecraft.net/bedrockdedicatedserver/bin-win/", "")

Tested and working for me after changing the two lines above.

**Comment by Bachperson** [comment]
Thanks for the info! updated the script to contain the new urls you provided.
